export const STANDALONE_SCHEMA_VERSION = 1;

export const STANDALONE_SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS local_profile (
    id TEXT PRIMARY KEY,
    display_name TEXT,
    default_currency TEXT NOT NULL DEFAULT 'AUD',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS module_settings (
    key TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS contracts (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    provider TEXT NOT NULL,
    contract_number TEXT,
    start_date TEXT,
    end_date TEXT,
    renewal_type TEXT NOT NULL DEFAULT 'MANUAL_RENEWAL',
    notice_period_days INTEGER,
    cost REAL,
    currency TEXT NOT NULL DEFAULT 'AUD',
    billing_frequency TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    contact_name TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    notes TEXT,
    reminder_days_before TEXT DEFAULT '30,14,7,1',
    is_tax_deductible INTEGER NOT NULL DEFAULT 0,
    property_id TEXT,
    vehicle_id TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE INDEX IF NOT EXISTS contracts_end_date_idx ON contracts(end_date)`,
  `CREATE INDEX IF NOT EXISTS contracts_status_idx ON contracts(status)`,
  `CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    manufacturer TEXT,
    model TEXT,
    vendor TEXT,
    serial_number TEXT,
    barcode TEXT,
    purchase_date TEXT,
    warranty_end_date TEXT,
    price REAL,
    currency TEXT NOT NULL DEFAULT 'AUD',
    notes TEXT,
    reminder_days_before TEXT DEFAULT '30,14,7,1',
    property_id TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE INDEX IF NOT EXISTS products_warranty_end_date_idx ON products(warranty_end_date)`,
  `CREATE TABLE IF NOT EXISTS vehicles (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    make TEXT,
    model TEXT,
    year INTEGER,
    colour TEXT,
    license_plate TEXT,
    vin TEXT,
    rego_expiry TEXT,
    insurance_expiry TEXT,
    reminder_days_before TEXT DEFAULT '30,14,7,1',
    notes TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE INDEX IF NOT EXISTS vehicles_rego_expiry_idx ON vehicles(rego_expiry)`,
  `CREATE INDEX IF NOT EXISTS vehicles_insurance_expiry_idx ON vehicles(insurance_expiry)`,
  `CREATE TABLE IF NOT EXISTS vehicle_items (
    id TEXT PRIMARY KEY,
    vehicle_id TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    provider TEXT,
    date TEXT,
    cost REAL,
    currency TEXT NOT NULL DEFAULT 'AUD',
    notes TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS vehicle_items_vehicle_id_idx ON vehicle_items(vehicle_id)`,
  `CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    storage_key TEXT NOT NULL UNIQUE,
    mime_type TEXT NOT NULL,
    size INTEGER NOT NULL,
    kind TEXT,
    extracted_text TEXT,
    uploaded_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE INDEX IF NOT EXISTS documents_owner_idx ON documents(owner_type, owner_id)`,
  `CREATE TABLE IF NOT EXISTS schema_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  )`,
  `INSERT OR REPLACE INTO schema_metadata (key, value)
    VALUES ('standalone_schema_version', '${STANDALONE_SCHEMA_VERSION}')`,
] as const;
